### ISSUE TITLE
需要一个更简单的安装教程。。

### ISSUE THREAD

**Issue by my4436927** [EmiyaGm/nonebot-plugin-lostark-wandering-trader#3]
nonebot装完了 但是文中说的NoneBot 全局配置文件是哪个 不知道

**Comment by EmiyaGm** [comment]
你找一下，有没有一个 .env 的文件，或者叫做 .env.prod

**Comment by my4436927** [comment]
> 你找一下，有没有一个 .env 的文件，或者叫做 .env.prod

有 但是
DRIVER=~fastapi
HOST=127.0.1.1  # 配置 NoneBot 监听的 IP / 主机名
PORT=35751  # 配置 NoneBot 监听的端口
COMMAND_START=["/"]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符
TRADER__USER_IDS=[QQ号]
TRADER__GROUP_IDS=[群号]
TRADER__TIME=1
TRADER__SERVER_ID=3
TRADER__RARITY=["Rare","Epic","Legendary"]
 是这样弄吗？

**Comment by EmiyaGm** [comment]
> 

对的，TRADER__USER_IDS=[QQ号] 里面的qq号替换成自己需要私聊通告的qq号，TRADER__GROUP_IDS=[群号] 里面的群号替换成自己需要通告的qq群群号

**Comment by my4436927** [comment]
> > 
> 
> 对的，TRADER__USER_IDS=[QQ号] 里面的qq号替换成自己需要私聊通告的qq号，TRADER__GROUP_IDS=[群号] 里面的群号替换成自己需要通告的qq群群号

但是。。我打开机器人后 这能收到消息 但是不会发送消息怎么办？

**Comment by EmiyaGm** [comment]
没听懂，什么叫做不会发送消息，能私聊，但是群里看不见机器人发的消息吗？

**Comment by my4436927** [comment]
> 没听懂，什么叫做不会发送消息，能私聊，但是群里看不见机器人发的消息吗？

机器人不会发消息。。

**Comment by my4436927** [comment]
机器人也成功登陆了 群的消息和私聊的消息都能收到 但是发 商人情况后 机器人不会 给任何回复。。

**Comment by EmiyaGm** [comment]
可能这个功能出了点问题，我看看哦，也麻烦您看一下插件的版本，确定一下是不是 0.1.0 这个版本

**Comment by my4436927** [comment]
nonebot_plugin_lostark_wandering_trader-0.1.0.dist-info  是这个版本吧？

**Comment by EmiyaGm** [comment]
> nonebot_plugin_lostark_wandering_trader-0.1.0.dist-info 是这个版本吧？

对的，那可能是功能出了点问题，我查一下

**Comment by my4436927** [comment]
> > nonebot_plugin_lostark_wandering_trader-0.1.0.dist-info 是这个版本吧？
> 
> 对的，那可能是功能出了点问题，我查一下

好的 麻烦了  是不是我缺了什么前置插件没装？没用过这个nonebot 只装了nonebot_plugin_lostark_wandering_trader", "nonebot_plugin_guild_patch", "nonebot_plugin_gocqhttp", "nonebot_plugin_color

**Comment by EmiyaGm** [comment]
可以看一下 nonebot_plugin_gocqhttp 的后台有没有什么报错的输出，我这边测试是没问题

阿尔忒弥斯的本出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
尤狄亚的卢卡斯出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
卢特兰西部的马龙出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
卢特兰东部的莫里斯出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
卢特兰东部的伯特出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
托托克的奥利弗出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
安亿谷的迈克出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
阿尔泰因的诺克斯出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
贝隆北部的彼得出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
休沙尔的杰弗里出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
洛恒戴尔的埃利塞出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
永恩的拉蒂尔出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
费顿的多雷拉出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
帕普妮卡的雷尼尔出现时间为：2023-08-18 10:00:00 - 2023-08-18 15:30:00
by: EmiyaGm


这应该是回复的输出

**Comment by my4436927** [comment]
> 可以看一下 nonebot_plugin_gocqhttp 的后台有没有什么报错的输出

没有报错 之前的报错全被我干掉了 他那个webui后台 群聊的列表打不开是这原因吗？

**Comment by EmiyaGm** [comment]
![02fe1588e2ca171d74ff2ac0bcfb7efc](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/11713728/d57f9e09-a50c-4b5d-b12b-b273c7c99553)

或者你重启一下机器人，然后私聊 商人情况 给机器人，看一下后台的输出

**Comment by my4436927** [comment]
![ANMG](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/49664943/696f3a88-7d65-4c6e-bcb2-6a4ebe20e062)

**Comment by my4436927** [comment]
这个群聊这边我选不了 是这个问题吗？

**Comment by EmiyaGm** [comment]
你应该是用命令启动的吧，去终端看一下终端的输出是什么

**Comment by my4436927** [comment]
![GFwww](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/49664943/6ae0b600-366b-4761-ad01-c5081b763cf9)
是这个吗。。一样的啊

**Comment by EmiyaGm** [comment]
下面没内容了吗，往下拉一点

**Comment by my4436927** [comment]
> 下面没内容了吗，往下拉一点

没了

**Comment by my4436927** [comment]
![HHHHH](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/49664943/bfda7cc5-6083-41e1-9ee5-aa726ddc6f71)

**Comment by EmiyaGm** [comment]
您通过一下我的机器人账号的申请，我看一下什么情况

**Comment by EmiyaGm** [comment]
应该是没有签名服务器，机器人被tx风控了

nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='52', message='send group message failed: blocked by server', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='send group message failed: blocked by server')

这是报错信息

可以去  go-cqhttp 这个项目里面找一下解决方案

**Comment by my4436927** [comment]
> 应该是没有签名服务器，机器人被tx风控了
> 
> nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='52', message='send group message failed: blocked by server', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='send group message failed: blocked by server')
> 
> 这是报错信息
> 
> 可以去 go-cqhttp 这个项目里面找一下解决方案

哦。。好的 我去找找方法
