### ISSUE TITLE
没有成功推送

### ISSUE THREAD

**Issue by Fsyxr** [EmiyaGm/nonebot-plugin-lostark-wandering-trader#5]
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/85301551/2a73741c-f1ae-4107-9d03-57a1db90cf0b)
这是我的配置，希里安区想推送传说的卡牌和好感度道具的
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/85301551/ad17d3d7-6d18-4994-824e-44ee5d580a01)
之前也正常推送过，但是不知道为什么又不行了。没有进行任何推送

**Comment by Fsyxr** [comment]
而且当前地图中有传说级的卡牌礼物，我重启bot变更配置文件也没有推送消息

**Comment by EmiyaGm** [comment]
麻烦看一下当前插件的版本，还有就是是群聊和私聊都不能推送了吗

**Comment by EmiyaGm** [comment]
嗯，我知道了，emrpg获取接口的数据格式变了，现在不会返回具体的信息了，要从另外三个接口去拿数据做比对，我调整一下插件逻辑

**Comment by Fsyxr** [comment]
好的，非常感谢

**Comment by EmiyaGm** [comment]
插件升级到 0.2.0 适配了接口的新数据格式，修复该问题

请更新插件
