### ISSUE TITLE
需要详细点安装流程

### ISSUE THREAD

**Issue by w9931125** [EmiyaGm/nonebot-plugin-lostark-wandering-trader#7]
感谢提供插件
在pyproject.toml里的[tool.nonebot] 没有找到这个参数
另外这个启动是setUp吗，怎么没有看到哪里授权我的qq号之类的。
新手，求解答

**Comment by EmiyaGm** [comment]
https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/issues/3

可以看一下这个 issue 的前几楼，你的配置文件找错了，该插件共用 nonebot 的配置文件

**Comment by EmiyaGm** [comment]
你得先确认你的机器人使用的是 nonebot 

https://nonebot.dev/

这是给 nonebot 机器人写的插件

**Comment by w9931125** [comment]
> 你得先确认你的机器人使用的是 nonebot
> 
> https://nonebot.dev/
> 
> 这是给 nonebot 机器人写的插件

感谢，我按照这个步骤安装了nonebot ，之后按照命令要求安装了此插件
之后我配置了config.py文件后 
在交互页面我输入Command 商人情况 没有返回商人信息，请问是哪里配置的不对吗，还有后续我怎么能够接入到qq群里
这是我的配置文件
from pydantic import BaseModel

class ScopedConfig(BaseModel):
    user_ids: list[int] = [766393779]
    group_ids: list[int] = [838691615]
    time: int = 1
    server_id: int = 12
    rarity: list[str] = []
    send_type: list[str] = []
    cards: list[str] = []
    location_image: bool = True


class Config(BaseModel):
    trader: ScopedConfig

**Comment by EmiyaGm** [comment]
额，插件的配置文件是 .env.prod 这个文件

**Comment by EmiyaGm** [comment]
TRADER__USER_IDS=[766393779]
TRADER__GROUP_IDS=[838691615]
TRADER__TIME=1
TRADER__SERVER_ID=12

然后在里面填入这些

**Comment by w9931125** [comment]
因为之前没弄过nonbot，今天补习了一下，然后又加入了go-cqhttp应该是这个吧？然后我这边账号已经可以登陆了。这个插件也运行起来了，只有不清楚怎么跟这个插件连接上，是通过ws方式还是http？我看这个项目起来后地址是127.0.0.1:8080，我应该怎么配置能连接上这个插件呢？如果我想的没错的话，连接上了直接发信息给登陆的qq就可以实现了吧

**Comment by EmiyaGm** [comment]
发消息这块不用你管，你应该是用 nonebot-plugin-gocqhttp 这个插件模拟的机器人qq号登录吧，你去看一下 https://github.com/mnixry/nonebot-plugin-gocqhttp 这个插件怎么使用的就行，然后正常安装我的插件，配置填在 .env.prod 这个文件里面就行了

**Comment by w9931125** [comment]
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/b8e3d1d5-465b-4cbc-b3c4-bc5b1af1dd34)
配置了之后启动发消息没有回复
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/d58b2501-1b79-4779-9839-22e0ff4947e8)

**Comment by EmiyaGm** [comment]
您是单独启动的 go-cqhttp 的服务是吧，能发一下您 go-cqhttp 的配置文件 config.yml 吗，我看一下您的配置

记得把密码打码

**Comment by w9931125** [comment]
<img width="849" alt="image" src="https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/3219fc1c-5fbc-4be8-b42f-1379b57be83e">

<img width="760" alt="image" src="https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/31112383-95f3-4db9-b443-20830235dc5d">

大概是这样的，启动go-cqhttp后插件会出这个异常
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/4c68594c-c26b-4244-9efb-22eaa3c656f3)
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/795abee9-042d-4aa8-bcf1-21c0c633d979)
我想应该是这里连接的问题，但不知道应该怎么配置，这两个插件都是在同一台机器🙏

**Comment by EmiyaGm** [comment]
`
universal: ws://127.0.0.1:8080/onebot/v11/ws
`

地址改一下

**Comment by w9931125** [comment]
OK 可以了 感谢楼主 除了商人情况，还有什么其他指令吗？

**Comment by EmiyaGm** [comment]
没有其他指令，因为反正会自动通报，想不到什么别的指令功能，如果你有好的想法，可以提issue

**Comment by w9931125** [comment]
![image](https://github.com/EmiyaGm/nonebot-plugin-lostark-wandering-trader/assets/52391192/9295099a-c47a-4320-8af2-33c9fcf51159)
发现了一个问题，播放时间要是设置60的话就报错了
